#!/usr/bin/env python3
"""Emit texts/tab_prefix_cache.tex — companion TABLE to
fig_O_agentic_react_cache. Summarizes, per engine, the effect of prefix
caching on a 30-turn ReAct trace:

  * median per-turn TTFT       (off -> on)
  * sigma of per-turn TTFT     (off -> on, the "fluctuation" caching kills)
  * worst-turn TTFT            (off -> on)
  * aggregate TTFT speedup     (sum over COMMON turns, off / on)

Imports the embedded measurements from the figure generator so the table
and the figure never diverge. Aggregate speedup is computed over the turns
present in BOTH the on and off series (llama.cpp's on series drops turns
1/5/8 as slot-promotion artifacts), so the ratio is apples-to-apples.
"""
from __future__ import annotations
import sys, statistics as st
from pathlib import Path

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
import gen_fig_O_agentic_react_cache as G  # noqa: E402

OUT = Path("/nvme/ispass/paper_jetson/JetsonAnalysis/texts/tab_prefix_cache.tex")

# paper engine order + macro names
ROWS = [("llama.cpp", r"\llamacpp{}"),
        ("SGLang",    r"\sglang{}"),
        ("vLLM",      r"\vllm{}")]


def stats(fw):
    off = {t: m for t, m, _, _ in G.DATA[fw]["off"]}
    on  = {t: m for t, m, _, _ in G.DATA[fw]["on"]}
    voff = list(off.values()); von = list(on.values())
    common = sorted(set(off) & set(on))
    agg_off = sum(off[t] for t in common)
    agg_on  = sum(on[t]  for t in common)
    med_on = st.median(von); mean_on = st.mean(von); sd_on = st.pstdev(von)
    return {
        "med_on": med_on, "mean_on": mean_on, "sd_on": sd_on,
        "cv_on": 100 * sd_on / mean_on,           # turn-to-turn jitter (%)
        "min_on": min(von), "max_on": max(von),
        "peak_ratio": max(von) / med_on,          # worst spike / typical
        "speedup": agg_off / agg_on,
        "n_common": len(common), "n_off": len(voff), "n_on": len(von),
    }


def ms(x):           # compact ms / s formatting, always with unit
    return f"{x/1000:.1f}\\,s" if x >= 1000 else f"{x:.0f}\\,ms"


def main():
    S = {fw: stats(fw) for fw, _ in ROWS}
    for fw, _ in ROWS:
        s = S[fw]
        print(f"{fw:<10} cache-on: median {s['med_on']:.0f}  "
              f"sigma {s['sd_on']:.0f}  CV {s['cv_on']:.0f}%  "
              f"peak {s['max_on']:.0f} ({s['peak_ratio']:.1f}x med)  "
              f"agg speedup {s['speedup']:.1f}x")

    lines = [
        r"% Auto-generated by figs/scripts/gen_tab_prefix_cache.py — do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Prefix caching on a 30-turn ReAct trace (Llama-3.2-1B"
        r" agentic loop). Caching gives every engine a low aggregate"
        r" time-to-first-token (TTFT, $10$--$20\times$ over no-cache), but the"
        r" \emph{stability} of the cached per-turn TTFT differs sharply:"
        r" \vllm{} and \sglang{} hold a tight, predictable profile"
        r" (CV ${\sim}30$--$35\%$), whereas \llamacpp{} still fluctuates"
        r" turn-to-turn (CV $79\%$, with spikes to $5.4\times$ its median)."
        r" $\sigma$ and CV are over the per-turn TTFT \emph{with caching on}.}",
        r"\label{tab:prefix-cache}",
        r"\small",
        r"\setlength{\tabcolsep}{5pt}",
        r"\begin{tabular}{@{}lccccc@{}}",
        r"\toprule",
        r" & agg.\ & \multicolumn{4}{c}{cache-on per-turn TTFT (fluctuation)} \\",
        r"\cmidrule(lr){3-6}",
        r"Engine & speedup & median & $\sigma$ & CV & peak \\",
        r"\midrule",
    ]
    for fw, mac in ROWS:
        s = S[fw]
        sup = s["speedup"]
        # llama.cpp on-series is 27 turns -> mark approximate
        sup_str = (f"$\\approx\\,{sup:.0f}\\times$" if s["n_on"] != s["n_off"]
                   else f"${sup:.1f}\\times$")
        lines.append(
            f"{mac} & {sup_str} & {ms(s['med_on'])} & {ms(s['sd_on'])} & "
            f"{s['cv_on']:.0f}\\% & {ms(s['max_on'])} \\\\")
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\par\vspace{2pt}\footnotesize",
        r"$\sigma$ / CV (=$\sigma$/mean) and peak are over the per-turn TTFT"
        r" with caching \emph{on}; peak is the worst single-turn TTFT. A high"
        r" CV means latency that, despite caching, still swings turn-to-turn."
        r" \llamacpp{} stats and aggregate are over the $27$ turns with valid"
        r" cache-on readings (turns 1/5/8 dropped as slot-promotion artifacts).",
        r"\end{table}",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    main()
